export const GET_TOURNAMENTS_BY_TERM_REQUEST = 'GET_TOURNAMENTS_BY_TERM_REQUEST';
export const GET_TOURNAMENTS_BY_TERM_SUCCESS = 'GET_TOURNAMENTS_BY_TERM_SUCCESS';
export const GET_TOURNAMENTS_BY_TERM_ERROR = 'GET_TOURNAMENTS_BY_TERM_ERROR';

export const ADD_TOURNAMENT_IN_BASKET = 'ADD_TOURNAMENT_IN_BASKET';
export const REMOVE_TOURNAMENT_FROM_BASKET = 'REMOVE_TOURNAMENT_FROM_BASKET';

export const CLEAR_TOURNAMENTS_SEARCH_RESULTS = 'CLEAR_TOURNAMENTS_SEARCH_RESULTS';
